# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bizpic',
            field=models.ImageField(default='img.jpg', upload_to='bizpic/'),
        ),
        migrations.AddField(
            model_name='business',
            name='mode',
            field=models.CharField(default='Amenity', max_length=255),
        ),
    ]
